<?php 
$baseurl = $block->getBaseUrl(); 
if($baseurl =="https://www.owensisters.com/" || $baseurl =="https://owensisters.com/" ){
?>
<div class="footerInfo">
<div class="copyright">© copyright 1974-2019 owensisters.com | Made With ❤ In London by <a style="color: #191919;" href="https://www.rvsmedia.co.uk/" target="_blank">RVS MEDIA</a></div>
</div>
<?php	
}else{
?>
<div class="footerInfo">
<div class="copyright">© copyright 1974-2019 owenbrotherscatering.com | Made With ❤ In London by <a style="color: #191919;" href="https://www.rvsmedia.co.uk/" target="_blank">RVS MEDIA</a></div>
</div>
<?php
} 
?>