<?php
$order = $block->getOrder();
$payment = $order->getPayment();
if ($payment && ($payment->getMethod()=='magenest_stripe_checkout')) {
    $sessionId = $payment->getAdditionalInformation("stripe_checkout_session_id");
}
$isCheckoutFinish = $payment->getAdditionalInformation("stripe_checkout_finish");
$publicKey = $block->getStripePublickey();
?>
<?php if (($payment->getMethod()=='magenest_stripe_checkout') && (!$isCheckoutFinish)) { ?>
    <br>
    Stripe Payment:
    <a href="#" class="action checkout" id="stripe_continue_checkout">
        <span>Continue checkout</span>
    </a>

    <script>
        require([
            'jquery',
            'https://js.stripe.com/v3/'
        ], function ($) {
            $('#stripe_continue_checkout').on("click", function () {
                var stripeSessionId = '<?= /* @noEscape */ $sessionId ?>';
                var stripe = Stripe('<?= /* @noEscape */ $publicKey ?>');
                stripe.redirectToCheckout({
                    sessionId: stripeSessionId
                }).then(function (result) {
                    if(result.error.message){
                        alert(result.error.message);
                    }
                });
            });
        });
    </script>
<?php } ?>
