<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$banners = $block->getFrontBanners();

?>


<article id="slider">
    
    
            <?php $i=1;  foreach($banners as $index => $banner){  ?>
                <input <?php if($i == 1): ?> checked="checked" <?php endif ?> type=radio name=slider id=<?php echo 'slide'. $i ?> />                    
            <?php  $i++; }   ?>
		
		<!-- The Slider -->
		
		<div id=slides>
		
			<div id=overflow>
			
				<div class="inner owl-carousel owlslider">
				
					<?php  foreach($banners as $index => $banner){ 
					
					?>
							<article>
								<div class="info <?php echo $banner->getLayoutbanner()?>">
									<?php echo $banner->getTitle();
										  echo $banner->getBannertext();
									?>
									<?php if($banner->getLink() != ''): ?><a target="<?php echo $banner->getTarget() ?>" href="<?php echo $banner->getLink() ?>">Shop Now</a><?php endif; ?>
								</div>
								<a target="<?php echo $banner->getTarget() ?>" href="<?php echo $banner->getLink() ?>">
								<img class="desktop-image" alt="<?php echo $banner->getTitle() ?>" src=<?php echo $block->getMediaDirectoryUrl().$banner->getBannerimage() ?> />
								<?php if(!empty($banner->getMobileimage())): ?>
									<img class="mobile-image" alt="<?php echo $banner->getTitle() ?>" src=<?php echo $block->getMediaDirectoryUrl().$banner->getMobileimage() ?> />
								<?php endif; ?>
								</a>
							</article>
					<?php   }   ?>
					
				</div> <!-- .inner -->
				
			</div> <!-- #overflow -->
		
		</div> <!-- #slides -->

		<!-- Controls and Active Slide Display -->
	
		<div id=controls>
                        <?php $i=1;  foreach($banners as $index => $banner){  ?>
                            <label for=<?php echo 'slide'. $i ?> id="<?php echo 'slide'. $i ?>"></label>
                        <?php $i++;  }   ?>
		</div> <!-- #controls -->
		
		<div class="slider-bullets" id=active>
                        <?php $i=1; foreach($banners as $index => $banner){  ?>
                            <label for=<?php echo 'slide'. $i ?> id="<?php echo 'slide'. $i ?>"></label>
                        <?php $i++;  }   ?>
		</div> <!-- #active -->

</article>

<script type="text/javascript">
    
var iPadLabels = function () {
			function fix() {
				var labels = document.getElementsByTagName('label'), 
					target_id, 
					el;
				for (var i = 0; labels[i]; i++) {
					if (labels[i].getAttribute('for')) {
						labels[i].onclick = labelClick;
					}
				}
			};
			function labelClick() {
				el = document.getElementById(this.getAttribute('for'));
				if (['radio', 'checkbox'].indexOf(el.getAttribute('type')) != -1) {
					el.setAttribute('selected', !el.getAttribute('selected'));
				} else {
					el.focus();
				}
			};
				return {
				fix: fix
			}
		}();
		
		window.onload = function () {
					
					iPadLabels.fix();
				
		}
                
</script>

<style type="text/css">
	
input[type=radio] {
	display: none;
}
</style>

<script>
	require(['jquery'],function($) {
		var intervalID = '';
		autoSlide();
		function autoSlide() {
			if($('.homeSlider .slider-bullets label').hasClass('active') && $('.homeSlider .slider-bullets label.active').next('label').length) {
				$('.homeSlider .slider-bullets label.active').next('label').trigger('click');
			}
			else {
				$('.homeSlider .slider-bullets label:first').trigger('click');
			}
			intervalID = setTimeout(autoSlide, 2000);
		}
		$('.homeSlider .slider-bullets label').mousedown( function(e) {
			clearTimeout(intervalID);
			autoSlide();
		});		
   	});
	
</script>
<script type="text/javascript">
require(['jquery'],function($){
	$(document).ready(function() {
      $(".inner").owlCarousel({
		items : 1, 
		nav:true,
		dots:false,
		loop:true,	
		autoplay:true,	
		autoplayTimeout: 3000, //Set AutoPlay to 3 seconds
		autoplayHoverPause:true	
      });     
    });
});	
</script>