<?php
/**
 * Copyright © 2018 Magenest. All rights reserved.
 */

$jsonData = $block->getStripeApplePayConfig();
$isInCatalog = $block->getIsInCatalogProduct();
$isCart = $block->getIsCart();
?>
<div class="payment-method"
     data-mage-init='{"Magenest_StripePayment/js/payment/stripe_button":{
        "is_catalog": "<?= /* @noEscape  */ boolval($isInCatalog) ?>",
        "is_cart": "<?= /* @noEscape  */ boolval($isCart) ?>",
        "json_data": <?= /* @noEscape  */ json_encode($jsonData) ?>
     }}'>
</div>


