<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_CheckoutCore
 */
?>
<?php
/** @var \Magento\Checkout\Block\Onepage $block */
/** @var \Amasty\Checkout\Helper\Onepage $helper */
/** @var \Amasty\Checkout\Model\Optimization\BundleService $bundleService */
// $helper = $block->getData('amcheckout_helper');
// $bundleService = $block->getData('bundleService');
// $design = $helper->isModernCheckoutDesign() ? 'modern' : 'classic';
// $layout = $helper->getDesignLayout();
$onepageDataProvider = $block->getData('amcheckoutOnepageDataProvider');
$bundleService = $block->getData('bundleService');
$styleSwitcher = $block->getData('amcheckoutStyleSwitcher');
$design = $styleSwitcher->isModernCheckoutDesign() ? 'modern' : 'classic';
$layout = $styleSwitcher->getDesignLayout();
$layoutTemplate = $styleSwitcher->getLayoutTemplate();

?>

<div id="checkout"
     data-bind="scope:'checkout'"
     class="checkout-container am-checkout -<?= /* @noEscape */ $design?> -layout-<?= /* @noEscape */ $layout?>"
     data-amcheckout-js="checkout">
    <div class="checkout-header">
        <h1 class="title"><?= $block->escapeHtml($onepageDataProvider->getTitle()); ?></h1>
        <div class="description"><?= /* @noEscape */ $onepageDataProvider->getDescription(); ?></div>
    </div>

    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?=
            /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?= $block->escapeHtml(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        require.config({
            config: {
                mixins: {
                    'Magento_Ui/js/view/messages': {
                        'Amasty_CheckoutCore/js/view/messages-mixin': true
                    }
                }
            }
        });
        window.checkoutConfig = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.checkoutDesign = "<?= $styleSwitcher->isModernCheckoutDesign() ? 'modern' : 'classic'?>";
        window.checkoutLayout = "<?= $block->escapeHtml($styleSwitcher->getLayoutTemplate())?>";
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?=
                /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?= /* @noEscape */ $block->getBaseUrl();?>');
        });
    </script>
<?php if ($bundleService->canCollectBundle()): ?>
    <script>
        require([
            'rjsResolver',
            'underscore',
            '<?= \Amasty\CheckoutCore\Model\Optimization\BundleService::COLLECT_SCRIPT_PATH ?>',
        ], function(requireResolver, _, createBundle) {
            requireResolver(_.debounce(createBundle, 1000));
        });
    </script>
<?php endif; ?>

</div>
